//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base64Pruebas2
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Revision { get; set; }
        public Nullable<bool> CargadoAElastic { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public Nullable<int> IdPadre { get; set; }
    }
}
